# Generated by Django 4.1.2 on 2022-12-19 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=30)),
                ('priority_level', models.CharField(max_length=30)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.BooleanField(default=django.utils.timezone.now)),
            ],
        ),
    ]
